(()=>{
'use strict';
const REPO='tilastomuuttujat/TTT',BRANCH='main',FILE='kirjoitukset.json';
const q=new URLSearchParams(location.search);if(q.get('admin')!=='1')return;
const slug=q.get('id')||'siilot-ja-sisapiirit',view=document.getElementById('frame');if(!view)return;
let token=sessionStorage.getItem('ttt_github_token')||'',data,article,index,dirty=false,editing=false,boundDoc=null;
const bar=document.createElement('div');bar.className='reader-adminbar';bar.innerHTML='<button id="ra-edit" class="primary">Muokkaa</button><button id="ra-preview">Esikatsele</button><button id="ra-cancel" disabled>Peruuta</button><button id="ra-save" disabled>Julkaise</button><button id="ra-account">GitHub</button><span class="reader-admin-status" id="ra-status">ADMIN · lukutila</span>';document.body.append(bar);
const login=document.createElement('div');login.className='reader-admin-login';login.hidden=!!token;login.innerHTML='<div class="reader-admin-card"><h2>TTT · Admin</h2><p>Anna GitHub fine-grained access token. Repositoryn tulee olla <b>tilastomuuttujat/TTT</b> ja oikeuden <b>Contents: Read and write</b>. Token säilyy vain tämän selainistunnon sessionStorage-muistissa.</p><input id="ra-token" type="password" autocomplete="off" placeholder="github_pat_…"><div class="reader-admin-actions"><button id="ra-readonly">Lukutilaan</button><button id="ra-login" class="primary">Avaa editori</button></div></div>';document.body.append(login);
const $=s=>document.querySelector(s),editBtn=$('#ra-edit'),previewBtn=$('#ra-preview'),saveBtn=$('#ra-save'),cancelBtn=$('#ra-cancel'),status=$('#ra-status');
$('#ra-login').onclick=()=>{const v=$('#ra-token').value.trim();if(!v)return;token=v;sessionStorage.setItem('ttt_github_token',v);login.hidden=true;status.textContent='ADMIN · lukutila'};$('#ra-readonly').onclick=()=>login.hidden=true;$('#ra-account').onclick=()=>{sessionStorage.removeItem('ttt_github_token');token='';$('#ra-token').value='';login.hidden=false};
const listOf=d=>Array.isArray(d)?d:(d.kirjoitukset||[]),clone=x=>JSON.parse(JSON.stringify(x));
function mark(){dirty=true;saveBtn.disabled=false;cancelBtn.disabled=false;status.textContent='ADMIN · julkaisemattomia muutoksia'}
function setAt(obj,path,val){let a=obj;for(let i=0;i<path.length-1;i++)a=a[path[i]];a[path[path.length-1]]=val}
function editable(el,path){if(!el)return;el.dataset.tttAdminPath=JSON.stringify(path);el.contentEditable=editing?'plaintext-only':'false';el.spellcheck=true;if(el.dataset.tttAdminBound)return;el.dataset.tttAdminBound='1';el.addEventListener('input',()=>{setAt(article,JSON.parse(el.dataset.tttAdminPath),el.innerText.trim());mark()})}
function installStyle(d){if(d.getElementById('ttt-admin-style'))return;const s=d.createElement('style');s.id='ttt-admin-style';s.textContent='.ttt-admin-editing [data-ttt-admin-path]{outline:1px dashed transparent;outline-offset:5px;border-radius:2px;transition:.15s}.ttt-admin-editing [data-ttt-admin-path]:hover{outline-color:rgba(181,76,42,.55);background:rgba(255,253,248,.55)}.ttt-admin-editing [data-ttt-admin-path]:focus{outline:2px solid #b54c2a;background:#fffdf8}';d.head.append(s)}
function bind(){const d=view.contentDocument;if(!d||!article)return;boundDoc=d;installStyle(d);editable(d.querySelector('.hero h1,.doc-title'),['title']);editable(d.querySelector('.dek,.doc-sub'),['subtitle']);const intro=[...d.querySelectorAll('.prose>.lead,.prose>.doc-intro,.doc-head .doc-intro')];(article.intro||[]).forEach((_,i)=>editable(intro[i],['intro',i]));(article.sections||[]).forEach((s,si)=>{const sec=d.getElementById(s.id);if(!sec)return;editable(sec.querySelector('h2,.doc-h2'),['sections',si,'title']);const ps=[...sec.children].filter(x=>x.tagName==='P'&&!x.classList.contains('num')&&!x.classList.contains('doc-closing'));(s.paragraphs||[]).forEach((_,pi)=>editable(ps[pi],['sections',si,'paragraphs',pi]));if(s.quote!=null)editable(sec.querySelector('blockquote'),['sections',si,'quote']);if(s.closing!=null)editable(sec.querySelector('.closing,.doc-closing'),['sections',si,'closing'])});toggle(editing)}
function toggle(on){editing=on;const d=view.contentDocument;if(!d)return;d.body.classList.toggle('ttt-admin-editing',on);d.querySelectorAll('[data-ttt-admin-path]').forEach(el=>el.contentEditable=on?'plaintext-only':'false');status.textContent=on?'ADMIN · muokkaustila':(dirty?'ADMIN · esikatselu':'ADMIN · lukutila');editBtn.textContent=on?'Muokkaus päällä':'Muokkaa'}
async function load(){data=await fetch('./'+FILE+'?t='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()});const l=listOf(data);index=l.findIndex(a=>(a.slug||a.id)===slug);if(index<0)throw Error('Artikkelia ei löytynyt');article=clone(l[index]);bind()}
view.addEventListener('load',()=>load().catch(e=>{console.error(e);status.textContent='Editorin lataus epäonnistui'}));
editBtn.onclick=()=>toggle(!editing);previewBtn.onclick=()=>toggle(false);cancelBtn.onclick=()=>{if(dirty&&confirm('Hylätäänkö julkaisemattomat muutokset?'))location.reload()};
async function gh(path,opt={}){const r=await fetch('https://api.github.com/repos/'+REPO+'/contents/'+path+(opt.get?'?ref='+BRANCH:''),{method:opt.method||'GET',headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body:opt.body?JSON.stringify(opt.body):undefined});if(!r.ok){const body=await r.text();if(r.status===403)throw Error('Tokenilla ei ole kirjoitusoikeutta. Tarkista TTT → Contents: Read and write.\n\n'+body);throw Error('GitHub '+r.status+': '+body)}return r.json()}
const b64=s=>btoa(unescape(encodeURIComponent(s)));
saveBtn.onclick=async()=>{if(!token){login.hidden=false;return}saveBtn.disabled=true;status.textContent='Tallennetaan GitHubiin…';try{const live=await fetch('./'+FILE+'?t='+Date.now(),{cache:'no-store'}).then(r=>r.json()),l=listOf(live),i=l.findIndex(a=>(a.slug||a.id)===(article.slug||article.id));if(i<0)throw Error('Artikkelia ei löytynyt nykyisestä JSONista');l[i]=article;const meta=await gh(FILE,{get:true});await gh(FILE,{method:'PUT',body:{message:'Update '+article.title+' [WYSIWYG]',content:b64(JSON.stringify(live,null,2)+'\n'),sha:meta.sha,branch:BRANCH}});dirty=false;cancelBtn.disabled=true;status.textContent='Julkaistu GitHubiin ✓';setTimeout(()=>status.textContent='ADMIN · lukutila',2200)}catch(e){console.error(e);alert('Julkaisu epäonnistui:\n'+e.message);saveBtn.disabled=false;status.textContent='Tallennus epäonnistui'}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
})();
